/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => KnowledgeAssistantPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/panel.ts
var import_obsidian = require("obsidian");
var KNOWLEDGE_ASSISTANT_VIEW_TYPE = "knowledge-assistant-view";
var KnowledgeAssistantPanel = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentTab = "search";
    this.searchHistory = [];
    this.plugin = plugin;
  }
  getViewType() {
    return KNOWLEDGE_ASSISTANT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Knowledge Assistant";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("ka-container");
    const header = container.createDiv({ cls: "ka-header" });
    header.createEl("h1", { text: "\u2B50 Knowledge Assistant", cls: "ka-title" });
    const statusDiv = header.createDiv({ cls: "ka-status" });
    this.updateStatusIndicator(statusDiv);
    const tabNav = container.createDiv({ cls: "ka-tabs" });
    const tabs = [
      { id: "search", label: "\u{1F50D} Search", icon: "search" },
      { id: "generate", label: "\u2728 Generate", icon: "wand" },
      { id: "stats", label: "\u{1F4CA} Stats", icon: "bar-chart" },
      { id: "settings", label: "\u2699\uFE0F Settings", icon: "settings" }
    ];
    const content = container.createDiv({ cls: "ka-content" });
    tabs.forEach((tab, index) => {
      const tabBtn = tabNav.createEl("button", {
        text: tab.label,
        cls: `ka-tab-btn ${tab.id === this.currentTab ? "active" : ""}`,
        attr: { "data-tab-id": tab.id }
      });
      tabBtn.addEventListener("click", () => this.switchTab(tab.id, content));
    });
    const searchPanel = content.createDiv({ cls: "ka-panel ka-search-panel" });
    const generatePanel = content.createDiv({ cls: "ka-panel ka-generate-panel" });
    const statsPanel = content.createDiv({ cls: "ka-panel ka-stats-panel" });
    const settingsPanel = content.createDiv({ cls: "ka-panel ka-settings-panel" });
    this.createSearchPanel(searchPanel);
    this.createGeneratePanel(generatePanel);
    this.createStatsPanel(statsPanel);
    this.createSettingsPanel(settingsPanel);
    this.showTab("search", content);
  }
  switchTab(tabId, content) {
    var _a;
    this.currentTab = tabId;
    const tabNav = (_a = content.parentElement) == null ? void 0 : _a.querySelector(".ka-tabs");
    if (tabNav) {
      tabNav.querySelectorAll(".ka-tab-btn").forEach((btn) => {
        btn.classList.remove("active");
      });
      const activeBtn = tabNav.querySelector(`.ka-tab-btn[data-tab-id="${tabId}"]`);
      if (activeBtn)
        activeBtn.classList.add("active");
    }
    this.showTab(tabId, content);
  }
  showTab(tabId, content) {
    content.querySelectorAll(".ka-panel").forEach((panel2) => {
      panel2.classList.remove("ka-panel-active");
    });
    const panel = content.querySelector(`.ka-${tabId}-panel`);
    if (panel)
      panel.classList.add("ka-panel-active");
  }
  createSearchPanel(panel) {
    const inputGroup = panel.createDiv({ cls: "ka-input-group" });
    const searchInput = inputGroup.createEl("input", {
      type: "text",
      placeholder: "Search your notes...",
      cls: "ka-input ka-search-input"
    });
    const searchButton = inputGroup.createEl("button", {
      text: "\u{1F50D} Search",
      cls: "ka-btn ka-btn-primary ka-search-btn"
    });
    const filterGroup = panel.createDiv({ cls: "ka-filter-group" });
    filterGroup.createEl("label", { text: "Number of results: ", cls: "ka-label" });
    const resultCountSelect = filterGroup.createEl("select", { cls: "ka-select" });
    [3, 5, 10, 20].forEach((num) => {
      const opt = resultCountSelect.createEl("option", { text: String(num) });
      opt.value = String(num);
      if (num === 5)
        opt.selected = true;
    });
    const resultsDiv = panel.createDiv({ cls: "ka-results-container" });
    const performSearch = () => {
      const query = searchInput.value.trim();
      if (query) {
        if (!this.searchHistory.includes(query)) {
          this.searchHistory.unshift(query);
          if (this.searchHistory.length > 10)
            this.searchHistory.pop();
        }
        const limit = parseInt(resultCountSelect.value);
        this.performSearch(query, resultsDiv, limit);
      }
    };
    searchButton.addEventListener("click", performSearch);
    searchInput.addEventListener("keypress", (e) => {
      if (e.key === "Enter")
        performSearch();
    });
    if (this.searchHistory.length > 0) {
      const historyDiv = panel.createDiv({ cls: "ka-history" });
      historyDiv.createEl("small", { text: "Recent searches:", cls: "ka-history-label" });
      this.searchHistory.slice(0, 3).forEach((term) => {
        const historyBtn = historyDiv.createEl("button", {
          text: term,
          cls: "ka-btn ka-btn-secondary ka-history-btn"
        });
        historyBtn.addEventListener("click", () => {
          searchInput.value = term;
          performSearch();
        });
      });
    }
  }
  createGeneratePanel(panel) {
    const inputGroup = panel.createDiv({ cls: "ka-input-group" });
    const generateInput = inputGroup.createEl("input", {
      type: "text",
      placeholder: "Ask about your notes...",
      cls: "ka-input ka-generate-input"
    });
    const generateButton = inputGroup.createEl("button", {
      text: "\u2728 Generate",
      cls: "ka-btn ka-btn-primary ka-generate-btn"
    });
    const infoDiv = panel.createDiv({ cls: "ka-info-box" });
    infoDiv.createEl("small", {
      text: "Uses RAG (Retrieval-Augmented Generation) to create intelligent responses based on your notes.",
      cls: "ka-info-text"
    });
    const resultsDiv = panel.createDiv({ cls: "ka-generated-container" });
    const performGeneration = () => {
      const query = generateInput.value.trim();
      if (query) {
        this.performGeneration(query, resultsDiv);
      }
    };
    generateButton.addEventListener("click", performGeneration);
    generateInput.addEventListener("keypress", (e) => {
      if (e.key === "Enter")
        performGeneration();
    });
  }
  createStatsPanel(panel) {
    panel.createEl("h3", { text: "Vault Statistics", cls: "ka-panel-title" });
    const statsContent = panel.createDiv({ cls: "ka-stats-grid" });
    statsContent.createEl("p", { text: "Loading statistics...", cls: "ka-loading" });
    this.loadStats(statsContent);
  }
  createSettingsPanel(panel) {
    panel.createEl("h3", { text: "Settings", cls: "ka-panel-title" });
    const settingsContent = panel.createDiv({ cls: "ka-settings-content" });
    const urlGroup = settingsContent.createDiv({ cls: "ka-setting-group" });
    urlGroup.createEl("label", { text: "Server URL:", cls: "ka-label" });
    const urlInput = urlGroup.createEl("input", {
      type: "text",
      value: this.plugin.settings.backendUrl,
      cls: "ka-input"
    });
    const testBtn = settingsContent.createEl("button", {
      text: "Test Connection",
      cls: "ka-btn ka-btn-secondary"
    });
    testBtn.addEventListener("click", () => {
      this.testConnection();
    });
    const indexGroup = settingsContent.createDiv({ cls: "ka-setting-group" });
    indexGroup.createEl("label", { text: "Index notes automatically:", cls: "ka-label" });
    const indexCheckbox = indexGroup.createEl("input", {
      type: "checkbox",
      cls: "ka-checkbox"
    });
    indexCheckbox.checked = this.plugin.settings.autoIndex;
    const saveBtn = settingsContent.createEl("button", {
      text: "Save Settings",
      cls: "ka-btn ka-btn-primary"
    });
    saveBtn.addEventListener("click", () => {
      this.plugin.settings.backendUrl = urlInput.value;
      this.plugin.settings.autoIndex = indexCheckbox.checked;
      this.plugin.saveSettings();
      new import_obsidian.Notice("Settings saved!");
    });
  }
  async performSearch(query, resultsDiv, limit = 5) {
    if (!resultsDiv)
      return;
    resultsDiv.empty();
    const loadingDiv = resultsDiv.createDiv({ cls: "ka-loading-spinner" });
    loadingDiv.createEl("div", { cls: "ka-spinner" });
    loadingDiv.createEl("p", { text: "Searching...", cls: "ka-loading-text" });
    const results = await this.plugin.searchVault(query, limit);
    resultsDiv.empty();
    if (!results) {
      const errorDiv = resultsDiv.createDiv({ cls: "ka-error-box" });
      errorDiv.createEl("p", { text: "\u274C Search failed. Please check the backend connection." });
      return;
    }
    if (results.results.length === 0) {
      const emptyDiv = resultsDiv.createDiv({ cls: "ka-empty-box" });
      emptyDiv.createEl("p", { text: "\u{1F4ED} No results found. Try a different search term." });
      return;
    }
    const header = resultsDiv.createDiv({ cls: "ka-results-header" });
    header.createEl("h4", { text: `\u2705 Found ${results.results.length} result${results.results.length !== 1 ? "s" : ""}:` });
    results.results.forEach((result, index) => {
      const resultCard = resultsDiv.createDiv({ cls: "ka-result-card" });
      const cardHeader = resultCard.createDiv({ cls: "ka-result-header" });
      cardHeader.createEl("strong", { text: `${index + 1}. ${result.metadata.file || "Unknown"}` });
      const similarity = ((1 - result.distance) * 100).toFixed(0);
      const badgeClass = parseInt(similarity) >= 80 ? "high" : parseInt(similarity) >= 50 ? "medium" : "low";
      const badge = cardHeader.createEl("span", {
        text: `${similarity}% relevant`,
        cls: `ka-badge ka-badge-${badgeClass}`
      });
      const content = resultCard.createDiv({ cls: "ka-result-content" });
      const preview = result.document.length > 300 ? result.document.substring(0, 300) + "..." : result.document;
      content.createEl("p", { text: preview });
      const footer = resultCard.createDiv({ cls: "ka-result-footer" });
      const openBtn = footer.createEl("button", {
        text: "\u{1F4D6} Open",
        cls: "ka-btn ka-btn-small"
      });
      openBtn.addEventListener("click", () => this.openFile(result.metadata.path));
      const copyBtn = footer.createEl("button", {
        text: "\u{1F4CB} Copy",
        cls: "ka-btn ka-btn-small"
      });
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(result.document);
        new import_obsidian.Notice("Content copied!");
      });
      const copyPathBtn = footer.createEl("button", {
        text: "\u{1F4CC} Path",
        cls: "ka-btn ka-btn-small"
      });
      copyPathBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(result.metadata.path);
        new import_obsidian.Notice("Path copied!");
      });
    });
  }
  async performGeneration(query, resultsDiv) {
    if (!resultsDiv)
      return;
    resultsDiv.empty();
    const loadingDiv = resultsDiv.createDiv({ cls: "ka-loading-spinner" });
    loadingDiv.createEl("div", { cls: "ka-spinner" });
    loadingDiv.createEl("p", { text: "Generating content...", cls: "ka-loading-text" });
    const result = await this.plugin.generateContent(query);
    resultsDiv.empty();
    if (!result) {
      const errorDiv = resultsDiv.createDiv({ cls: "ka-error-box" });
      errorDiv.createEl("p", { text: "\u274C Content generation failed. Please check the backend connection." });
      return;
    }
    const contentCard = resultsDiv.createDiv({ cls: "ka-generated-card" });
    contentCard.createEl("h4", { text: "\u2728 Generated Response", cls: "ka-card-title" });
    const contentDiv = contentCard.createDiv({ cls: "ka-generated-content" });
    contentDiv.createEl("p", { text: result.content });
    const copyBtn = contentCard.createEl("button", {
      text: "\u{1F4CB} Copy Response",
      cls: "ka-btn ka-btn-secondary"
    });
    copyBtn.addEventListener("click", () => {
      navigator.clipboard.writeText(result.content);
      new import_obsidian.Notice("Response copied!");
    });
    if (result.context && result.context.length > 0) {
      const contextCard = resultsDiv.createDiv({ cls: "ka-context-card" });
      contextCard.createEl("h4", { text: `\u{1F4DA} Context Used (${result.context.length} documents)`, cls: "ka-card-title" });
      result.context.forEach((ctx, index) => {
        const ctxItem = contextCard.createDiv({ cls: "ka-context-item" });
        ctxItem.createEl("strong", { text: `${index + 1}. ${ctx.metadata.file}`, cls: "ka-context-title" });
        const preview = ctx.document && ctx.document.length > 150 ? ctx.document.substring(0, 150) + "..." : ctx.document || "[Empty]";
        ctxItem.createEl("p", { text: preview, cls: "ka-context-preview" });
        const openBtn = ctxItem.createEl("button", {
          text: "\u{1F4D6} Open",
          cls: "ka-btn ka-btn-tiny"
        });
        openBtn.addEventListener("click", () => this.openFile(ctx.metadata.path));
      });
    }
  }
  async loadStats(container) {
    var _a, _b, _c, _d;
    const stats = await this.plugin.getStats();
    container.empty();
    if (!stats) {
      container.createEl("p", { text: "\u274C Cannot connect to the backend server.", cls: "ka-error" });
      return;
    }
    const statsGrid = container.createDiv({ cls: "ka-stats-grid" });
    const docCard = statsGrid.createDiv({ cls: "ka-stat-card" });
    docCard.createEl("div", { text: "\u{1F4C4}", cls: "ka-stat-icon" });
    docCard.createEl("div", { text: String(stats.total_documents), cls: "ka-stat-value" });
    docCard.createEl("div", { text: "Documents", cls: "ka-stat-label" });
    const llmCard = statsGrid.createDiv({ cls: "ka-stat-card" });
    const llmStatus = ((_a = stats.llm) == null ? void 0 : _a.available) ? ((_b = stats.llm) == null ? void 0 : _b.loaded) ? "\u2705" : "\u23F3" : "\u26A0\uFE0F";
    llmCard.createEl("div", { text: llmStatus, cls: "ka-stat-icon" });
    llmCard.createEl("div", { text: ((_c = stats.llm) == null ? void 0 : _c.available) ? "AI on" : ((_d = stats.llm) == null ? void 0 : _d.enabled) ? "Disabled" : "Fallback", cls: "ka-stat-value" });
    llmCard.createEl("div", { text: "AI Model Status", cls: "ka-stat-label" });
    if (stats.vault_path) {
      const pathCard = statsGrid.createDiv({ cls: "ka-stat-card ka-stat-path" });
      pathCard.createEl("strong", { text: "Vault Path:" });
      pathCard.createEl("code", { text: stats.vault_path, cls: "ka-path-text" });
    }
  }
  async testConnection() {
    try {
      const stats = await this.plugin.getStats();
      if (stats) {
        new import_obsidian.Notice("\u2705 Connection successful!");
      } else {
        new import_obsidian.Notice("\u274C Connection failed");
      }
    } catch (e) {
      new import_obsidian.Notice("\u274C Error connecting to backend");
    }
  }
  async updateStatusIndicator(container) {
    try {
      const stats = await this.plugin.getStats();
      if (stats) {
        const statusEl = container.createDiv({ cls: "ka-status-indicator ka-status-online" });
        statusEl.createEl("span", { text: "\u25CF Online", cls: "ka-status-text" });
      }
    } catch (e) {
      const statusEl = container.createDiv({ cls: "ka-status-indicator ka-status-offline" });
      statusEl.createEl("span", { text: "\u25CF Offline", cls: "ka-status-text" });
    }
  }
  async openFile(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file) {
      await this.app.workspace.openLinkText(path, "", true);
    }
  }
  async onClose() {
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  backendUrl: "http://127.0.0.1:5000",
  vaultPath: "C:\\Users\\HP\\Documents\\Obsidian Vault",
  autoIndex: true
};
var KnowledgeAssistantPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    const cssContent = await this.loadCSSAsString();
    if (cssContent) {
      const styleEl = document.createElement("style");
      styleEl.textContent = cssContent;
      styleEl.id = "ka-styles";
      document.head.appendChild(styleEl);
    }
    this.addRibbonIcon("star", "Knowledge Assistant", () => {
      this.activatePanel();
    });
    this.addCommand({
      id: "open-knowledge-assistant",
      name: "Open Knowledge Assistant",
      callback: () => {
        this.activatePanel();
      }
    });
    this.addCommand({
      id: "search-selection",
      name: "Search selection in vault",
      callback: () => {
        this.searchSelection();
      }
    });
    this.addCommand({
      id: "generate-from-selection",
      name: "Generate content from selection",
      callback: () => {
        this.generateFromSelection();
      }
    });
    this.addSettingTab(new KnowledgeAssistantSettingTab(this.app, this));
    this.registerView(
      "knowledge-assistant-view",
      (leaf) => new KnowledgeAssistantPanel(leaf, this)
    );
    if (this.settings.autoIndex) {
      this.indexVault();
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async loadCSSAsString() {
    try {
      const response = await fetch(this.manifest.dir + "/styles.css");
      if (response.ok) {
        return await response.text();
      }
    } catch (e) {
      console.warn("Could not load CSS file, using inline styles");
    }
    return "";
  }
  activatePanel() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType("knowledge-assistant-view")[0];
    if (!leaf) {
      const newLeaf = workspace.getRightLeaf(false);
      if (newLeaf) {
        newLeaf.setViewState({ type: "knowledge-assistant-view", active: true });
        workspace.revealLeaf(newLeaf);
      }
    } else {
      workspace.revealLeaf(leaf);
    }
  }
  async searchSelection() {
    var _a, _b;
    const activeView = (_a = this.app.workspace.activeLeaf) == null ? void 0 : _a.view;
    if (!activeView)
      return;
    const selection = (_b = activeView.editor) == null ? void 0 : _b.getSelection();
    if (selection) {
      this.activatePanel();
      setTimeout(() => {
        const leaf = this.app.workspace.getLeavesOfType("knowledge-assistant-view")[0];
        if (leaf && leaf.view instanceof KnowledgeAssistantPanel) {
          leaf.view.performSearch(selection);
        }
      }, 100);
    } else {
      new import_obsidian2.Notice("No text selected");
    }
  }
  async generateFromSelection() {
    var _a, _b;
    const activeView = (_a = this.app.workspace.activeLeaf) == null ? void 0 : _a.view;
    if (!activeView)
      return;
    const selection = (_b = activeView.editor) == null ? void 0 : _b.getSelection();
    if (selection) {
      this.activatePanel();
      setTimeout(() => {
        const leaf = this.app.workspace.getLeavesOfType("knowledge-assistant-view")[0];
        if (leaf && leaf.view instanceof KnowledgeAssistantPanel) {
          leaf.view.performGeneration(selection);
        }
      }, 100);
    } else {
      new import_obsidian2.Notice("No text selected");
    }
  }
  async indexVault() {
    try {
      const response = await fetch(`${this.settings.backendUrl}/index`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        }
      });
      if (response.ok) {
        new import_obsidian2.Notice("Vault indexed successfully");
      } else {
        new import_obsidian2.Notice("Failed to index vault");
      }
    } catch (error) {
      new import_obsidian2.Notice("Error connecting to backend. Make sure the Python server is running.");
    }
  }
  async searchVault(query, nResults = 5) {
    try {
      const response = await fetch(`${this.settings.backendUrl}/search`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          query,
          n_results: nResults
        })
      });
      if (response.ok) {
        return await response.json();
      } else {
        throw new Error("Search failed");
      }
    } catch (error) {
      new import_obsidian2.Notice("Error performing search");
      return null;
    }
  }
  async generateContent(query, nResults = 3) {
    try {
      const response = await fetch(`${this.settings.backendUrl}/generate`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          query,
          n_results: nResults
        })
      });
      if (response.ok) {
        return await response.json();
      } else {
        throw new Error("Generation failed");
      }
    } catch (error) {
      new import_obsidian2.Notice("Error generating content");
      return null;
    }
  }
  async getStats() {
    try {
      const response = await fetch(`${this.settings.backendUrl}/stats`);
      if (response.ok) {
        return await response.json();
      }
    } catch (error) {
      console.error("Error getting stats", error);
    }
    return null;
  }
};
var KnowledgeAssistantSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Knowledge Assistant Settings" });
    new import_obsidian2.Setting(containerEl).setName("Backend URL").setDesc("URL of the Python backend server").addText((text) => text.setPlaceholder("http://127.0.0.1:5000").setValue(this.plugin.settings.backendUrl).onChange(async (value) => {
      this.plugin.settings.backendUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Vault Path").setDesc("Path to your Obsidian vault (for the backend)").addText((text) => text.setPlaceholder("/path/to/vault").setValue(this.plugin.settings.vaultPath).onChange(async (value) => {
      this.plugin.settings.vaultPath = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Auto-index on startup").setDesc("Automatically index vault when plugin loads").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoIndex).onChange(async (value) => {
      this.plugin.settings.autoIndex = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Index Vault Now").setDesc("Manually trigger vault indexing").addButton((button) => button.setButtonText("Index").onClick(async () => {
      await this.plugin.indexVault();
    }));
    new import_obsidian2.Setting(containerEl).setName("Connection Status").setDesc("Check if backend is running").addButton((button) => button.setButtonText("Check Connection").onClick(async () => {
      const stats = await this.plugin.getStats();
      if (stats) {
        let status = `Connected! ${stats.total_documents} documents indexed`;
        if (stats.llm && stats.llm.available) {
          status += stats.llm.loaded ? " | LLM: Ready" : " | LLM: Configured but not loaded";
        } else {
          status += " | LLM: Not configured (using template generation)";
        }
        new import_obsidian2.Notice(status);
      } else {
        new import_obsidian2.Notice("Cannot connect to backend");
      }
    }));
  }
};
